services:
  #  carrent:
  #    container_name: "carrent"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: carrent-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - private_network
    volumes:
      - sql_data:/var/opt/mssql

networks:
  private_network:
    driver: bridge

volumes:
  sql_data:
    driver: local