spring:
  application:
    name: carrent-api

  # Database
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=carrent_db;encrypt=false;trustServerCertificate=false
    username: sa
    password: YourStrong!Passw0rd
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: none

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

jwt:
  key: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000
